#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM banzaicloud/spark:latest

# `Z_VERSION` will be updated by `dev/change_zeppelin_version.sh`
ENV Z_VERSION="0.9.0-SNAPSHOT"
COPY "zeppelin-$Z_VERSION/zeppelin-$Z_VERSION/conf" /opt/zeppelin/conf
COPY "zeppelin-$Z_VERSION/zeppelin-$Z_VERSION/lib/interpreter" /opt/zeppelin/lib/interpreter
COPY "zeppelin-$Z_VERSION/zeppelin-$Z_VERSION/interpreter/spark" /opt/zeppelin/interpreter/spark

ENTRYPOINT [ "/opt/entrypoint.sh" ]
